/**
 * LinearProgrammingSimulator.tsx: Class 12 Linear Programming (LPP) Lab.
 * Features:
 * - Convex feasible region polygon generated by linear inequalities in first quadrant
 * - Corner Point Method: Automatic vertex calculation and Z-value evaluation
 * - Sliding Iso-Profit line Z = ax + by demonstrating the Fundamental Theorem of LPP
 * - Maximization vs Minimization toggle
 * - 3 Progressive Board Exam challenges
 */
import React, { useMemo } from 'react';
import confetti from 'canvas-confetti';
import { 
  Maximize2, 
  RotateCcw, 
  Sparkles, 
  Layers, 
  TrendingUp, 
  CheckCircle2,
  Sliders
} from 'lucide-react';
import { useSimulatorStore } from '../../store/useSimulatorStore';
import { BottomSheet } from '../layout/BottomSheet';
import { TouchSlider } from '../common/TouchSlider';
import { CoachTheoryModule } from '../common/CoachTheoryModule';
import { ChallengeManager, ChallengeLevel } from '../common/ChallengeManager';
import { useHaptics } from '../../hooks/useHaptics';
import { useSound } from '../common/SoundManager';
import { useAnalytics } from '../../hooks/useAnalytics';
import { LiveSubstitutionCard } from '../common/LiveSubstitutionCard';

export const LinearProgrammingSimulator: React.FC = () => {
  const {
    linearProgParams,
    updateLinearProgParams,
    resetParams,
    completeChallenge,
    challengeCompleted,
    isZenMode,
  } = useSimulatorStore();

  const {
    objectiveMaximize,
    profitX,
    profitY,
    constraint1_limit,
    constraint2_limit,
    showFeasibleRegion,
    showIsoProfitSlider,
    isoProfitValue,
  } = linearProgParams;

  const { lightTap, successBuzz } = useHaptics();
  const { playClick, playChime } = useSound();
  const { trackEvent } = useAnalytics();

  // Constraints:
  // C1: x + 2y <= constraint1_limit (default 8) -> intercepts: (8, 0), (0, 4)
  // C2: 3x + 2y <= constraint2_limit (default 12) -> intercepts: (4, 0), (0, 6)
  // Intersection of C1 and C2:
  // (3x + 2y) - (x + 2y) = 2x = 12 - 8 = 4 => x = 2
  // 2 + 2y = 8 => y = 3
  const c1 = constraint1_limit;
  const c2 = constraint2_limit;

  const cornerPoints = useMemo(() => {
    // Intersect 3x + 2y = c2 and x + 2y = c1
    // 2x = c2 - c1 => x = (c2 - c1)/2
    const intX = Math.max(0, (c2 - c1) / 2);
    const intY = Math.max(0, (c1 - intX) / 2);

    const pt0 = { label: 'O', x: 0, y: 0 };
    const pt1 = { label: 'A', x: Math.min(c1, c2 / 3), y: 0 };
    const pt2 = { label: 'B', x: intX, y: intY };
    const pt3 = { label: 'C', x: 0, y: Math.min(c1 / 2, c2 / 2) };

    const pts = [pt0, pt1, pt2, pt3].map((pt) => ({
      ...pt,
      z: profitX * pt.x + profitY * pt.y,
    }));

    return pts;
  }, [c1, c2, profitX, profitY]);

  // Determine optimum
  const optimalPoint = useMemo(() => {
    if (objectiveMaximize) {
      return cornerPoints.reduce((max, pt) => (pt.z > max.z ? pt : max), cornerPoints[0]);
    } else {
      return cornerPoints.reduce((min, pt) => (pt.z < min.z ? pt : min), cornerPoints[0]);
    }
  }, [cornerPoints, objectiveMaximize]);

  const handleReset = () => {
    lightTap();
    playClick();
    resetParams('linear-programming-lab');
  };

  const challengeLevels: ChallengeLevel[] = [
    {
      levelNumber: 1,
      title: 'Maximum Profit at Intersection B(2, 3)',
      badge: 'LPP Strategist',
      description: 'Set profit coefficients to Z = 5x + 4y. Find the maximum profit vertex at point B(2, 3)!',
      requirementFormula: 'Z(B) = 5(2) + 4(3) = 10 + 12 = 22',
      targetCriteria: 'Set profitX=5, profitY=4 with maximize=true',
      xpReward: 35,
      tier1Hint: 'Set Profit coefficient X to 5.',
      tier2Hint: 'Set Profit coefficient Y to 4.',
      tier3Hint: 'Check the Corner Point table: Z(A)=20, Z(B)=22, Z(C)=16. The maximum is 22 at B(2,3)!',
      autoPreset: () => {
        updateLinearProgParams({ profitX: 5, profitY: 4, objectiveMaximize: true });
      },
    },
    {
      levelNumber: 2,
      title: 'Heavily Skewed Profit toward X',
      badge: 'Resource Allocator',
      description: 'Increase profit on X to 10 while keeping Y = 2. Notice the maximum flips to point A(4, 0)!',
      requirementFormula: 'Z(A) = 10(4) + 2(0) = 40 > Z(B) = 26',
      targetCriteria: 'Set profitX=10 and profitY=2',
      xpReward: 40,
      tier1Hint: 'Slide Profit on X to 10.',
      tier2Hint: 'Slide Profit on Y to 2.',
      tier3Hint: 'When product X is far more lucrative, allocating all resources to X yields highest profit!',
      autoPreset: () => {
        updateLinearProgParams({ profitX: 10, profitY: 2, objectiveMaximize: true });
      },
    },
    {
      levelNumber: 3,
      title: 'Iso-Profit Sweep Verification',
      badge: 'Corner Point Master',
      description: 'Slide the Iso-Profit line to the optimal value to see it touch the boundary of the feasible polygon at exactly the optimum corner!',
      requirementFormula: 'Z = 5x + 4y = 22',
      targetCriteria: 'Slide isoProfitValue to match optimal Z',
      xpReward: 50,
      tier1Hint: 'Enable Iso-Profit line slider.',
      tier2Hint: 'Drag the slider to match the optimal value calculated in the table.',
      tier3Hint: 'The iso-profit line is the last point of contact before leaving the feasible region!',
      autoPreset: () => {
        updateLinearProgParams({ showIsoProfitSlider: true, isoProfitValue: optimalPoint.z });
      },
    },
  ];

  // Challenge checks
  React.useEffect(() => {
    if (!challengeCompleted["level-1"] && profitX === 5 && profitY === 4 && objectiveMaximize) {
      completeChallenge("level-1", 35);
      successBuzz();
      playChime();
      confetti({ particleCount: 40, spread: 60 });
    }
    if (!challengeCompleted["level-2"] && profitX === 10 && profitY === 2 && optimalPoint.label === 'A') {
      completeChallenge("level-2", 40);
      successBuzz();
      playChime();
      confetti({ particleCount: 50, spread: 70 });
    }
    if (!challengeCompleted["level-3"] && showIsoProfitSlider && Math.abs(isoProfitValue - optimalPoint.z) < 1) {
      completeChallenge("level-3", 50);
      successBuzz();
      playChime();
      confetti({ particleCount: 60, spread: 80 });
    }
  }, [profitX, profitY, objectiveMaximize, optimalPoint, showIsoProfitSlider, isoProfitValue, challengeCompleted, completeChallenge, successBuzz, playChime]);

  const controlsContent = (
    <div className="space-y-4 text-slate-200">
      <LiveSubstitutionCard
        title="LPP Corner Point Evaluation"
        badge={objectiveMaximize ? 'Max Z' : 'Min Z'}
        symbolicLaw="Z = c_1 x + c_2 y, \quad \text{Optimum at Extreme Vertex}"
        substitutedLatex={`Z(${optimalPoint.label}) = (${profitX})(${optimalPoint.x.toFixed(1)}) + (${profitY})(${optimalPoint.y.toFixed(1)})`}
        evaluatedLatex={`Z^* = ${optimalPoint.z.toFixed(2)} \\quad \\text{at } ${optimalPoint.label}(${optimalPoint.x.toFixed(1)}, ${optimalPoint.y.toFixed(1)})`}
      />

      <div className="flex bg-slate-900 p-1 rounded-2xl border border-slate-800">
        <button
          onClick={() => {
            lightTap();
            updateLinearProgParams({ objectiveMaximize: true });
          }}
          className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all ${
            objectiveMaximize ? 'bg-cyan-500 text-slate-950 shadow-md' : 'text-slate-400 hover:text-white'
          }`}
        >
          Maximize Profit (Max Z)
        </button>
        <button
          onClick={() => {
            lightTap();
            updateLinearProgParams({ objectiveMaximize: false });
          }}
          className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all ${
            !objectiveMaximize ? 'bg-amber-500 text-slate-950 shadow-md' : 'text-slate-400 hover:text-white'
          }`}
        >
          Minimize Cost (Min Z)
        </button>
      </div>

      <div className="space-y-4">
        <TouchSlider
          label="Profit / Weight on X (c₁)"
          value={profitX}
          min={1}
          max={12}
          step={1}
          unit=" ₹/unit"
          onChange={(val) => updateLinearProgParams({ profitX: val })}
        />

        <TouchSlider
          label="Profit / Weight on Y (c₂)"
          value={profitY}
          min={1}
          max={12}
          step={1}
          unit=" ₹/unit"
          onChange={(val) => updateLinearProgParams({ profitY: val })}
        />

        <TouchSlider
          label="Constraint 1 Capacity (x + 2y ≤ C₁)"
          value={constraint1_limit}
          min={6}
          max={12}
          step={1}
          unit=""
          onChange={(val) => updateLinearProgParams({ constraint1_limit: val })}
        />

        <TouchSlider
          label="Constraint 2 Capacity (3x + 2y ≤ C₂)"
          value={constraint2_limit}
          min={8}
          max={16}
          step={1}
          unit=""
          onChange={(val) => updateLinearProgParams({ constraint2_limit: val })}
        />
      </div>

      <div className="pt-2">
        <button
          onClick={() => {
            lightTap();
            updateLinearProgParams({ showIsoProfitSlider: !showIsoProfitSlider });
          }}
          className={`w-full py-2.5 rounded-xl font-bold text-xs flex items-center justify-center gap-2 border transition-all ${
            showIsoProfitSlider
              ? 'bg-cyan-500 text-slate-950 border-cyan-400'
              : 'bg-slate-900 border-slate-800 text-slate-300'
          }`}
        >
          <Sliders className="w-4 h-4" />
          {showIsoProfitSlider ? 'Hide Iso-Profit Line' : 'Show Iso-Profit Line Sweep'}
        </button>

        {showIsoProfitSlider && (
          <div className="mt-3">
            <TouchSlider
              label="Iso-Profit Level (Z)"
              value={isoProfitValue}
              min={0}
              max={60}
              step={1}
              unit=""
              onChange={(val) => updateLinearProgParams({ isoProfitValue: val })}
            />
          </div>
        )}
      </div>
    </div>
  );

  return (
    <div className="min-h-full flex flex-col bg-slate-950 text-slate-100 p-3 sm:p-6 pb-32">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div>
          <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-cyan-900/40 text-cyan-400 border border-cyan-700/40">
            Class 12 • Linear Programming
          </span>
          <h1 className="text-xl sm:text-2xl font-black text-white mt-1 flex items-center gap-2">
            <TrendingUp className="w-6 h-6 text-cyan-400" />
            Linear Programming & Corner Point Method
          </h1>
        </div>
        <button
          onClick={handleReset}
          className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-slate-200 border border-slate-800"
          title="Reset Parameters"
        >
          <RotateCcw className="w-4 h-4" />
        </button>
      </div>

      <div className="w-full max-w-4xl mx-auto bg-slate-900/70 border border-slate-800/80 rounded-3xl p-5 sm:p-6 backdrop-blur-sm shadow-xl space-y-6">
          {/* Target Objective Display */}
          <div className="bg-slate-950/80 rounded-2xl p-4 border border-cyan-950/60 text-center">
            <span className="text-xs text-slate-400 uppercase font-semibold">Objective Function</span>
            <div className="text-2xl font-mono font-bold text-cyan-300 mt-0.5">
              {objectiveMaximize ? 'Maximize' : 'Minimize'} Z = {profitX}x + {profitY}y
            </div>
            <div className="text-xs font-mono text-emerald-400 mt-1">
              Optimum: Z = <strong className="text-white font-bold">{optimalPoint.z.toFixed(1)}</strong> at Vertex {optimalPoint.label}({optimalPoint.x.toFixed(1)}, {optimalPoint.y.toFixed(1)})
            </div>
          </div>

          {/* SVG Feasible Region Canvas */}
          <div className="bg-slate-950/80 rounded-2xl p-4 border border-slate-800/80 flex items-center justify-center min-h-[300px]">
            <svg viewBox="-1 -1 10 9" className="w-full max-w-sm h-auto transform scale-y-[-1]">
              {/* Axes */}
              <line x1="-0.5" y1="0" x2="8.5" y2="0" stroke="#475569" strokeWidth="0.08" />
              <line x1="0" y1="-0.5" x2="0" y2="7.5" stroke="#475569" strokeWidth="0.08" />

              {/* Constraint 1 line: x + 2y = c1 */}
              <line x1="0" y1={c1 / 2} x2={c1} y2="0" stroke="#06b6d4" strokeWidth="0.08" strokeDasharray="0.3,0.3" />

              {/* Constraint 2 line: 3x + 2y = c2 */}
              <line x1="0" y1={c2 / 2} x2={c2 / 3} y2="0" stroke="#f59e0b" strokeWidth="0.08" strokeDasharray="0.3,0.3" />

              {/* Feasible Region Polygon */}
              <polygon
                points={cornerPoints.map(p => `${p.x},${p.y}`).join(' ')}
                fill="rgba(6, 182, 212, 0.25)"
                stroke="#06b6d4"
                strokeWidth="0.1"
              />

              {/* Corner Points */}
              {cornerPoints.map((pt, idx) => {
                const isOptimal = pt.label === optimalPoint.label;
                return (
                  <circle
                    key={idx}
                    cx={pt.x}
                    cy={pt.y}
                    r={isOptimal ? 0.25 : 0.16}
                    fill={isOptimal ? '#10b981' : '#ffffff'}
                    stroke={isOptimal ? '#ffffff' : '#06b6d4'}
                    strokeWidth="0.06"
                  />
                );
              })}
            </svg>
          </div>

          {/* Corner Points Evaluation Table */}
          <div className="bg-slate-950/60 rounded-xl p-4 border border-slate-800 space-y-2">
            <div className="text-xs font-bold text-slate-300 flex items-center justify-between">
              <span>Corner Point Method Table:</span>
              <span className="text-[11px] text-cyan-400 font-mono">Z = {profitX}x + {profitY}y</span>
            </div>
            <div className="grid grid-cols-4 gap-2 text-center text-xs font-mono">
              {cornerPoints.map((pt) => {
                const isOptimal = pt.label === optimalPoint.label;
                return (
                  <div
                    key={pt.label}
                    className={`p-2 rounded-lg border ${
                      isOptimal
                        ? 'bg-emerald-950/50 border-emerald-500 text-emerald-300 font-bold shadow-md'
                        : 'bg-slate-900 border-slate-800 text-slate-400'
                    }`}
                  >
                    <div>{pt.label}({pt.x.toFixed(1)}, {pt.y.toFixed(1)})</div>
                    <div className="text-sm font-bold text-white mt-1">Z = {pt.z.toFixed(0)}</div>
                    {isOptimal && <div className="text-[9px] uppercase tracking-wide text-emerald-400">Optimum</div>}
                  </div>
                );
              })}
            </div>
          </div>
        </div>

      <BottomSheet
        title="Linear Programming Lab"
        onReset={handleReset}
        theoryContent={<CoachTheoryModule simulatorId="linear-programming-lab" />}
        challengeContent={
          <ChallengeManager
            simulatorId="linear-programming-lab"
            simulatorTitle="Linear Programming Lab"
            levels={challengeLevels}
          />
        }
      >
        {controlsContent}
      </BottomSheet>
    </div>
  );
};
